### Numpy

Question 1: Create a NumPy array of integers from 1 to 10.

In [1]:
import numpy as np

arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


Question 2: Reshape the array from Question 1 into a 2x5 matrix.



In [2]:
arr_reshaped = arr.reshape(2,5)
print(arr_reshaped)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


Question 3: Create a 3x3 identity matrix using NumPy.



In [7]:
identity_matrix = np.identity(3)
print(identity_matrix)

# or

identity_matrix2 = np.eye(3)
print(identity_matrix2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Question 4: Multiply two NumPy arrays element-wise.



In [8]:
a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8])

product = a1*a2
print(product)


[ 5 12 21 32]


Question 5: Calculate the mean, median, and standard deviation of an array.



In [9]:
arr = np.array([10, 20, 30, 40, 50])
print("Mean: ", np.mean(arr))
print("Median: ", np.median(arr))
print("Standard Deviation: ", np.std(arr))

Mean:  30.0
Median:  30.0
Standard Deviation:  14.142135623730951


Question 6: Concatenate two NumPy arrays vertically.



In [10]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])

c_arr = np.vstack((arr1,arr2))
print(c_arr)

[[1 2]
 [3 4]
 [5 6]]


Question 7: Find the index of the maximum value in a NumPy array.



In [11]:
arr = np.arange(1,101,10)
print(arr)

print("Index of Maximum Value: ", np.argmax(arr))

[ 1 11 21 31 41 51 61 71 81 91]
Index of Maximum Value:  9


Question 8: Perform element-wise addition of a scalar to a NumPy array.



In [12]:
arr = np.array([1, 2, 3, 4])
scalar = 5
result = arr + scalar
print(result)

[6 7 8 9]


Question 9: Check if any element in a NumPy array satisfies a condition.



In [13]:
arr = np.array([1, 2, 3, 4, 5])
any_greater_than_3 = np.any(arr > 3)
print("Any element > 3:", any_greater_than_3)

Any element > 3: True


Question 10: Calculate the dot product of two NumPy arrays.



a = (a1, a2, a3)

b = (b1, b2, b3)

a.b = (a1b1 + a2b2 + a3b3)

In [14]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

dot_product = np.dot(arr1, arr2)
print("Dot product:", dot_product)

Dot product: 32
