In [1]:
import numpy as np

Create a null vector of size 10 but the fifth value which is 1.

In [2]:
null_vector = np.zeros(10)
null_vector[4] = 1

print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

In [5]:
def create_array(a,b):

    arr = np.zeros((a,b))
    arr[0,:] = 1
    arr[-1,:] = 1
    arr[:,[0,-1]] = 1
    return arr

print(create_array(5,7))


[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


Create a vector of size 10 with values ranging from 0 to 1, both excluded.

In [6]:
vector = np.linspace(0, 1, 12)[1:-2]

print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182]


Create a 5x5 matrix with row values ranging from 0 to 4.

In [10]:
matrix = np.tile(np.arange(5), (5, 1))
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


Consider a random integer (in range 1 to 100) vector with shape (10,2) representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

In [11]:
random_vector = np.random.randint(1, 101, size=(10, 2))

given_point = np.array([2, 3])

distances = np.sqrt(((random_vector - given_point)**2).sum(axis=1))
distances = distances.astype(int)

print(distances)

[  2 109 107  55 106  68  72  88  53  68]


Subtract the mean of each row from a matrix.

In [12]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
result_matrix = matrix - np.mean(matrix, axis=1, keepdims=True)

print(result_matrix)

[[-1.  0.  1.]
 [-1.  0.  1.]]


Swap column-1 of array with column-2 in the array.

In [13]:
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

array[:, [0, 1]] = array[:, [1, 0]]

print("Array after swapping column-1 with column-2:")
print(array)

Array after swapping column-1 with column-2:
[[2 1 3]
 [5 4 6]
 [8 7 9]]


Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

Input: a = np.array([1,2,3])

Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [17]:
def pattern_arr(arr):

    p1 = np.repeat(arr,3)
    for i in range(3):
        p1 = np.append(p1,arr)
    return p1

print(pattern_arr(np.array([1,2,3])))

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


Given two arrays of same shape make an array of max out of two arrays. (Numpy way)

In [18]:
array1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

array2 = np.array([[9, 8, 7],
                   [6, 5, 4],
                   [3, 2, 1]])

max_array = np.maximum(array1, array2)

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\nArray of max values:")
print(max_array)

Array 1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array 2:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Array of max values:
[[9 8 7]
 [6 5 6]
 [7 8 9]]


Replace odd elements in arrays with -1.

In [19]:
array = np.where(array % 2 == 1, -1, array)

print("Array after replacing odd elements with -1:")
print(array)

Array after replacing odd elements with -1:
[[ 2 -1 -1]
 [-1  4  6]
 [ 8 -1 -1]]
